### PR TITLE
tabular regression docs

### LINKED ISSUE #359: Tabular-regression Task Page
This is the tracker for completion of task page for `tabular-regression` task. The page is here: https://huggingface.co/tasks/tabular-regression. You can contribute parts of a task or the whole task! (There's no single assignee to a task, these are wikipedia-like pages)
You can refer to https://github.com/huggingface/hub-docs/issues/369 if you want to contribute! 🤗

List of items to contribute:
- [x] Task description
- [x] Subtasks (if there is any)
- [x] Most used dataset for the task
- [x] Most used model for the task
- [ ] Metrics that are used to evaluate the task
- [ ] Libraries used for the task
- [ ] Use cases
- [ ]  Small snippet for inference that demonstrates the task

### PR DESCRIPTION
**Pull request by brendenconnors**
Updates to

Task description
Subtasks (NA)
Datasets
Models

Not really any great model with card on HF for this so I trained one and uploaded with skops for use.

Fixes #359 
@merveenoyan 

@nlsschim tagging you as you said you would like to contribute in the issue, maybe you can fork from here!

### CODE REVIEW

File: tasks/src/tabular-regression/data.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+		{
+			description: "Dataset containing tip amounts for food servers.",
+			id:          "scikit-learn/tips",
+		},
+		{
+			description: "Dataset containing mile-per-gallon (mpg) information for various vehicles",
+			id:          "scikit-learn/auto-mpg",
+		},
+		{
+			description: "Dataset containing measurements of fish at a market.",
```
Comment (merveenoyan) [inline tasks/src/tabular-regression/data.ts:17]: I think the above two are enough 🙂 WDYT?

File: tasks/src/tabular-regression/data.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+					["165", "178"],
+					["170", "165"]
+
+				],
+				type: "tabular",
+			},
+		],
+		outputs: [
+			{
+				table: [["Baby's Height (cm)"], ["47"], ["50"], ["51"]],
```
Comment (merveenoyan) [inline tasks/src/tabular-regression/data.ts:36]: Looks good to me, but I feel like it would be good to put a business case, e.g. a small subset of auto-mpg dataset's columns 

Ekran Resmi 2022-10-10 20 37 59

File: tasks/src/tabular-regression/data.ts [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+	id:        "tabular-regression",
+	label:     PIPELINE_DATA["tabular-regression"].name,
+	libraries: TASKS_MODEL_LIBRARIES["tabular-regression"],
+	metrics:   [
+		
+	],
+	models: [
+		{
+			description: "Fish weight prediction based on length measurements and species.",
+			id:          "brendenc/Fish-Weight",
```
Comment (merveenoyan) [inline tasks/src/tabular-regression/data.ts:50]: I really loved how you put the model card, would you like to demo it on scikit-learn organization on 🤗 Hub? it's where we put good examples 🙂

File: tasks/src/tabular-regression/data.ts [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+		},
+	],
+	summary:
+		"Tabular regression is the task of predicting a numerical value given a set of attributes/features.",
```
Comment (merveenoyan) [inline tasks/src/tabular-regression/data.ts:54]:
```suggestion
		"Tabular regression is the task of predicting a numerical value given a set of attributes.",
```
feel free to ignore if it makes no sense, thought it would look better

File: tasks/src/tabular-regression/about.md [hunk 5]
```diff
@@ -0,0 +1,17 @@
+## About the Task
+
+Tabular regression is the task of predicting a numerical value given a set of attributes/features. *Tabular* meaning that data is stored in a table (like an excel sheet), and each sample is contained in its own row. The features used to predict our target can be both numerical and categorical. However, including categorical features often requires  additional preprocessing/feature engineering (a few models do accept categorical features directly, like [CatBoost](https://catboost.ai/)). An example of tabular regression would be predicting the weight of a fish given its' species (categorical) and length (numerical).
```
Comment (merveenoyan) [inline tasks/src/tabular-regression/about.md:3]: I feel like on the last sentence when you write down the type of data at the parenthesis it feels like the emphasis should be on features and not the target. WDYT?

**Review by merveenoyan — APPROVED** [review]
I really liked this! Happy to merge after we address the comments 🙂

File: tasks/src/tabular-regression/data.ts (hunk 1 above)
Comment (brendenconnors) [reply tasks/src/tabular-regression/data.ts:17]: Yes agreed. I will drop one!

File: tasks/src/tabular-regression/data.ts (hunk 2 above)
Comment (brendenconnors) [reply tasks/src/tabular-regression/data.ts:36]: Sounds good!

File: tasks/src/tabular-regression/data.ts (hunk 3 above)
Comment (brendenconnors) [reply tasks/src/tabular-regression/data.ts:50]: Yes that would be awesome 🙂 How should I go about that, do I need to get added to the org?

File: tasks/src/tabular-regression/about.md (hunk 5 above)
Comment (brendenconnors) [reply tasks/src/tabular-regression/about.md:3]: Yes I think it is maybe a bit distracting, as tabular regression is defined mostly by the target and not the features.

That being said, do you think the sentences

'''
 The features used to predict our target can be both numerical and categorical. However, including categorical features often requires  additional preprocessing/feature engineering (a few models do accept categorical features directly, like [CatBoost](https://catboost.ai/)).
'''
are unnecessary/distracting?

File: tasks/src/tabular-regression/data.ts (hunk 2 above)
Comment (brendenconnors) [reply tasks/src/tabular-regression/data.ts]: Updated using auto-mpg, let me know if you want to include more features.

File: tasks/src/tabular-regression/data.ts (hunk 3 above)
Comment (merveenoyan) [reply tasks/src/tabular-regression/data.ts:46]: I accepted you in the org 🙂

File: tasks/src/tabular-regression/about.md (hunk 5 above)
Comment (merveenoyan) [reply tasks/src/tabular-regression/about.md]: I think I'm fine with the sentence :)

**Comment by brendenconnors** [comment]
Model moved to scikit-learn org and redirect changed @merveenoyan 

I will notify that these pieces have been filled out in the issue, and will pick up the rest if others don't follow through. 
Thanks so much 🙂

**Comment by merveenoyan** [comment]
@brendenconnors congratulations! I'll also add your handle at the end of the docs 🙂
